name: Network CI/CD

on:

  push:

    branches:
      - main

  pull_request:

jobs:

  validate:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5

      with:
        python-version: '3.11'

    - name: Install Ansible

      run: |
        pip install ansible
        pip install ansible-lint

    - name: Install VyOS Collection

      run: |
        ansible-galaxy collection install vyos.vyos

    

  deploy:

    needs: validate

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: Deploy Containerlab

      run: |
        sudo containerlab deploy \
        -t containerlab/topology.yml

    - name: Configure VyOS

      run: |
        ansible-playbook \
          -i ansible/inventory.yml \
          ansible/site.yml

    - name: Verify

      run: |
        ansible-playbook \
          -i ansible/inventory.yml \
          tests/verify.yml