name: Network CI/CD

on:

  push:

    branches:
      - main

  pull_request:

jobs:

  validate:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5

      with:
        python-version: '3.11'

    - name: Install Ansible

      run: |
        pip install ansible
        pip install ansible-lint

    - name: Install LAB Collection

      run: |
        ansible-galaxy collection list
